### ISSUE TITLE
Replace usage of "best-effort" with "time-permitting"

### ISSUE THREAD

**Issue by mhdawson** [pkgjs/support#24]
We changed from `best-effort` to `time-permitting` in https://github.com/nodejs/package-maintenance/blob/main/docs/PACKAGE-SUPPORT.md

We should update all of the tests so use  `time-permitting` to be consistent with that.

**Comment by helio-frota** [comment]
yup I can do that :+1:

**Comment by helio-frota** [comment]
I think this issue can be closed.
