### ISSUE TITLE
how can we have these cool badges?

### ISSUE THREAD

**Issue by helio-frota** [pkgjs/support#31]
![2020-11-25_07-28](https://user-images.githubusercontent.com/6443576/100215625-fbb5f700-2eef-11eb-8d3c-57328263d73a.png)

**Comment by richardlau** [comment]
https://shields.io/ is one option. 

e.g.
https://img.shields.io/badge/support%20backing-HOBBY-blue
![https://img.shields.io/badge/support%20backing-HOBBY-blue](https://img.shields.io/badge/support%20backing-HOBBY-blue)

https://img.shields.io/badge/support%20target-LTS-orange
![https://img.shields.io/badge/support%20target-LTS-orange](https://img.shields.io/badge/support%20target-LTS-orange)

https://img.shields.io/badge/support%20response-best--effort-yellow
![https://img.shields.io/badge/support%20response-best--effort-yellow](https://img.shields.io/badge/support%20response-best--effort-yellow)

**Comment by helio-frota** [comment]
@richardlau thank you that works :+1:
