### ISSUE TITLE
Add files section to package.json to avoid to publish test fixture files

### ISSUE THREAD

**Issue by helio-frota** [pkgjs/support#33]
Currently npm shows 157 files 

```
Unpacked Size 
74.6 kB

Total Files
157
```

That is because `support` was published with test fixtures:

```console
$ tar -tf pkgjs-support-0.0.3.tgz 
package/test/cli/show-local-circular-dependency/command
package/test/cli/show-local-escape-ok/command
package/test/cli/show-local-escape/command
package/test/cli/show-local-path1/command
package/test/cli/show-local-path2/command
package/test/cli/show-local-tree-flat/command
package/test/cli/show-local-tree/command
package/test/cli/show-local/command
...
```

It would be good to have a `files` section on package.json to avoid publishing fixture files.

**Comment by ljharb** [comment]
There’s disagreement on that front. I believe all npm packages should always publish all tests, so that `npm explore foo && npm install && npm test` always works.

**Comment by helio-frota** [comment]
@ljharb interesting and I just learned about the existence of `npm explore`. Thanks for share your opinion. :+1: 
So yeah, in that case I'm ok on closing this issue.
