### ISSUE TITLE
Add command to add basic support info

### ISSUE THREAD

**Issue by mhdawson** [pkgjs/support#39]
Add command `create` which will create basic info, co-ordinate with adding info through https://github.com/pkgjs/create (ie use same internals etc.)

**Comment by wesleytodd** [comment]
Technical requirements:

- read existing package.json and support info
- provide single line cli command with east defaults (like `-y` should work)
- using npm's package (cant remember the name off hand) to read normalized package.json and `json-file-plus` to write it without formatting mess ups
- sharing the internals of the work on @pkgjs/create would be great to help it interop

**Comment by rodion-arr** [comment]
I'd like to give this a try after few clarifications:

- should this command write full `support` object to `package.json` or we can write it to `package-support.json` and put `true` to main `package.json`?
- what are support file defaults? Based on [this example](https://github.com/pkgjs/support/blob/master/examples/basic.json) - I can propose next values (without backing as it requires to get link from somewhere):

```json
{
  "versions": [{
    "version": "*",
    "target": {
      "node": "lts"
    },
    "response": {
      "type": "time-permitting"
    }
  }]
}
```

**Comment by ljharb** [comment]
We should pick a default, but let users choose inline vs file.

**Comment by ljharb** [comment]
For backing, if there’s a .github/FUNDING.yml, or a funding field in package.json, those backing sources should be used.

**Comment by mhdawson** [comment]
@rodion-arr thanks!

I don't believe we support inline, from https://github.com/nodejs/package-maintenance/blob/HEAD/docs/PACKAGE-SUPPORT.md

```markdown
A new field called support is added to package.json. The contents of this field will be one of the following:

true: This will indicate that the canonical version of the support information for the package is available in a file within the repository specified by the repository entry. In this case the filepath for the file containing the support information will be ./package-support.json
a string: a relative path, starting with ./, that points to a file within the repository specified in the repository entry which contains the canonical support information.
object, with repository key matching the schema for the existing repository entry, and optional path field that complies with the format described above under a string
```
I think to start,  supporting the simplest option of setting the field in package.json to `true` and writing the package-support.json in the same directory would cover the largest portion of the use cases.

What would be good is to populate with what data can re-use (form example as @ljharb mentioned the funding info), and then ask user a few questions with defaults filled in.  It should probably also handle the case where there is an existing file (or at least prevent overwriting and existing file).

In terms of defaults  I'm not sure we should have a default for the target, that one I think it might make sense to force people to read/choose one as otherwise people might just choose the default and it won't be correct.  

For the `backing` field. For that I'd suggest a default of `hobby` without any other link as we say the URL is optional.

**Comment by rodion-arr** [comment]
Thanks, clear for me regarding defaults.

However I'm afraid I still not quite understand how these changes should correlate with `create` package. New command should be built with same tools as was used in `create`? E.g. `opta`, `fs-test-fixtures`, so it could potentially have easy migration into `create` in future?

**Comment by ljharb** [comment]
@rodion-arr ideally, the "create package" tool should:
 1. create a package
 1. add funding into to it
 1. add support info to it
 1. etc
 
 and each individual step of that should be its own CLI/package so it can be used independently

**Comment by mhdawson** [comment]
Adding to that, the reason create package was mentioned is that when you create a package it will need to support adding the package-support info and it should use the support package to do that

**Comment by rodion-arr** [comment]
Hey, just wanted to update that I'm in progress on this, finishing with tests and docs updates. Going to submit PR till end of week.

**Comment by mhdawson** [comment]
@rodion-arr, great to hear!
