### ISSUE TITLE
create command offers 'best-effort' for response type

### ISSUE THREAD

**Issue by shadowspawn** [pkgjs/support#43]
I used `create` to seed the support information for a project I maintain. I spent a while wondering whether I should use `time-permitting` or `best-effort`, and could not find a description of what `best-effort` meant in the spec.

On further investigation, I found `best-effort` has been replaced by `time-permitting`: #24 #29

But it snuck back in through #40 and is currently offered in the user interface when using `create`.

**Comment by rodion-arr** [comment]
Thanks, I'll submit a PR to address this.
