### ISSUE TITLE
Support relative paths and remote `package-support.json`

### ISSUE THREAD

**Issue by wesleytodd** [pkgjs/support#5]
Reference: https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/PACKAGE-SUPPORT.md#integration-into-packagejson

**Comment by mhdawson** [comment]
I think this has been covered, @wesleytodd please re-open if I'm wrong on that.

**Comment by wesleytodd** [comment]
I will close this, as I am guessing that was your intent.
