### ISSUE TITLE
MVP definition

### ISSUE THREAD

**Issue by mhdawson** [pkgjs/support#6]
We had a meeting yesterday to agree on what the MVP would be. Some notes on the discussion in: https://docs.google.com/document/d/1THGBeRMBkfUoQ6VqFXG9nNM-j4vbrfmk3lIfHTjBea

What I believe we agreed to was that the MVP needs to include:

* **Validation for maintainer** adding the support info for their modules
  * Validation of local file
  * Validation of package.json which includes links support info

*  **Listing support info for end users**  wanting to understand the support info provided
    by the modules they are using in their deployments.  Agreed that MVP can focus on
    using information which available locally versus pulling canonical version from remote
    repository,

**Comment by mhdawson** [comment]
@wesleytodd, @Eomm, @ljharb

**Comment by wesleytodd** [comment]
Sorry, super late on this.  Yes that is as I remember.

**Comment by mhdawson** [comment]
I think we've implemented the MVP closing.
